[package]
name = "jeprof-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.21.0"
nom = "7.1.3"
object = "0.32.2"
